name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Doker login
      env:
        DOCKER_USER: ${{ DOCKER_USER }}
        DOCKER_PASSWORD: ${{ DOCKER_PASSWORD }}
      run: |
        echo "Started login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Finalized login" 
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
